sonar.projectKey={process.env.SONAR_PROJECT_KEY}
sonar.organization={process.env.SONAR.ORGANIZATION}
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
